"""
Django settings for ndr_core project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/

# PyPI-Token: pypi-AgENdGVzdC5weXBpLm9yZwIkMWM5NzE2MzEtZjM4My00MmUxLWJjMDgtYjBhNjdmMjVjYWE2AAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCp36thAms1p2VbkuxN6TCyJVBrSVCZ8jQ7r9x-Vz7lAQ
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.contrib import messages

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tv6meg%j0=z2(d37_7hb(2t%+zeiq45hw=o0d$kcbz)*2no97s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'ndr_core_api',
    'main',
    'django_static_fontawesome',
    'bootstrap4',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ndr_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ndr_core_api.context_processors.info_bite',
                'ndr_core_api.context_processors.carousel_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'ndr_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CORS_ALLOW_ALL_ORIGINS = True # If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
CORS_ALLOW_CREDENTIALS = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
}


EMAIL_HOST = 'mail.flunk.com'
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = 'no-reply@divisive-power.org'


NDR_CORE_API_CONFIG = {
    "www-host": "divisive-power.org",
    "header_title": "DPCL - Divisive Power Of Citizenship",
    "header_author": "Christian Futter, Peter Cornwell, Madeleine Herren-Oesch, Sorin Marti",
    "header_description": "This repository is an outcome of the Europa Institute Basel research program of the same "
                          "name, funded by Swiss National Science Foundation under grant 100011_184860/1.",
    "website_title": "Welcome To DPC",
    "contact-from-email": "no-reply@divisive-power.org",
    "contact-recipients": ['info@data-futures.org', ],

    "main_view": "main:index",
    "search_view": "main:search",

    "footer_text": "(c) 2022, Institute For European Global Studies",

    "use_dummy_result": False,
    "repositories": {
        "dpc": {
            "dummy_result_file": "main/dummy_result_dpc.json",
            "api_host": "dpcdata.int",
            "api_protocol": "http",
            "api_port": 80,
            "label": "DPCL - Divisive Power of Citizenship and Loyalty"
        },
        "asiadir": {
            "dummy_result_file": "main/dummy_result_asiadir.json",
            "api_host": "hpedata.int",
            "api_protocol": "http",
            "api_port": 80,
            "label": "Asian Directories and Chronicles"
        },
        "haka": {
            "dummy_result_file": "main/dummy_result_asiadir.json",
            "api_host": "handelskammerdata.int",
            "api_protocol": "http",
            "api_port": 80,
            "label": "Handelskammer",
            "query_type": "basic"
        }
    },

    "page_size": 10,
    "search_fields":
        {
            "name": {
                "type": "string",
                "help_text": "Insert a Last Name.",
                "api_param": "surname",
            },
            "first_name": {
                "type": "string",
                "help_text": "Insert First Name Initials or Titles.",
                "api_param": "givennames"
            },
            "tags": {
                "type": "dictionary",
                "api_param": "tags",
                "dictionary": {
                    "type": "tsv",
                    "file": "main/tag_list.tsv",
                    "search_column": 0,
                    "display_column": 1,
                    "has_title_row": True
                },
                "widget": "multi_search",
                "help_text": "Note: Most Data Entries for this Category are unknown."
            },
            "organization": {
                "type": "string",
                "help_text": "Insert an Organisation Name (e.g. Company, Governments, Department, School, etc.).",
                "api_param": "organisation"
            },
            "profession": {
                "type": "string",
                "help_text": "Insert a Profession (e.g. Missionary, Merchant, Wharfinger, etc.)."
            },
            "location": {
                "type": "string",
                "required": False,
                "api_param": "location",
                "help_text": "Search for locations. You may select multiple. If left blank, all locations are searched."
            },
            "year": {
                "type": "number",
                "api_param": "year",
            }
        },
    "form_display": [
        [
            {"name": "name", "size": "4"},
            {"name": "first_name", "size": "3"},
            {"name": "tags", "size": "5"}
        ],
        [
            {"name": "organization", "size": "6"},
            {"name": "profession", "size": "6"},
        ],
        [
            {"name": "location", "size": "8"},
            {"name": "year", "size": "4"},
        ],
    ],

        "configurations": {
            "advanced": ["__all__", ]
        }
    }