# Generated by Django 3.2.7 on 2022-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NdrCorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the page', max_length=200)),
                ('label', models.CharField(help_text='The label of the page', max_length=200)),
                ('view_name', models.CharField(help_text='The name of the view', max_length=200)),
                ('nav_icon', models.CharField(help_text='The fontawesome nav icon', max_length=200)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
    ]
