# Generated by Django 3.2.7 on 2022-08-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndr_core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndrcorepage',
            name='label',
            field=models.CharField(help_text="The label of the page, e.g. the page's navigation label", max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcorepage',
            name='name',
            field=models.CharField(help_text="The name of the page, e.g. the page's title", max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcorepage',
            name='nav_icon',
            field=models.CharField(blank=True, help_text='The fontawesome nav icon (leave blank if none)', max_length=200),
        ),
        migrations.AlterField(
            model_name='ndrcorepage',
            name='view_name',
            field=models.CharField(help_text='The name of the view to display', max_length=200),
        ),
    ]
